require_relative "action.rb"

Vagrant.configure("2") do |config|
  config.vm.define "docker-provider"

  config.vm.box = "yungsang/coreos"

  config.vm.provider "virtualbox" do |v, override|
    override.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.provider "parallels" do |p, override|
    override.vm.network "private_network", ip: "192.168.34.10"
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true, type: "nfs"
end
