# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "yungsang/boot2docker"
  
  config.vm.network :private_network, ip: "192.168.33.10"
 
  config.vm.synced_folder "..", "/vagrant", type: "nfs"
 
  config.vm.network :forwarded_port, guest: 8080, host: 8080
 
  config.vm.provision :docker do |d|
    d.build_image "/vagrant/", args: "-t hello-docker"
    d.run "hello-docker", args: "-p 8080:80 -v /vagrant:/vagrant"
  end
end
